### PR TITLE
Gzip Me Up: Add gzipping flag to publish gzipped resources to S3

### PR DESCRIPTION
**Pull request by Shadowfiend**
Resources are gzipped in-memory before transmission to S3, where
they are properly marked with Content-Encoding: gzip.

This also fixes the snapshot version to 0.5.0-SNAPSHOT.

### CODE REVIEW

**Comment by farmdawgnation** [comment]
Lol. Heyyyyyy @Shadowfiend :D

**Comment by Shadowfiend** [comment]
Oof. Lemme try and give this a look tomorrow or late tonight.

**Comment by Shadowfiend** [comment]
Have a look at dat.

**Comment by farmdawgnation** [comment]
I'm down. Let's do it.

**Pull request merged**
